### ISSUE TITLE
Initialising the APN client in an init method  

### ISSUE THREAD

**Issue by moadqassem** [mercari/gaurun#10]
Hello,

After looking at the pushNotificationWorker method, the apnClient gets initialized after we check whether its null or not, so why its not initilized just like the Android client inside an init method?

**Comment by cubicdaiya** [comment]
At the start, `gaurun` keeps TCP connections for GCM and APNs.


`gaurun` communicates to GCM with HTTPS and its HTTPS client belongs to [`net/http`](http://golang.org/pkg/net/http/). `net/http`'s client caches TCP connections transparently. So it is not requierd to handle TCP connections directly for communicating to GCM.


On the other hand, APNs is based TLS and original binary protocol. It is required to handle TCP connections directly for communicating to APNs. (e.g. A connection to APNs is sometimes closed.)


So `pushNotificationWorker()` requires the implementation for handling the connection to APNs directly.

**Comment by moadqassem** [comment]
I see, honestly I had  a feeling that the connection may expires because I saw expire property somewhere in their documentation, so I thought that might be the case, however you are basically keep continuing till you initilize a valid connection for the apn so what would happen if non of the goroutines have established a valid connection to the APN, and you have an android push notification you will never send the android notification because the code snippet which is responsible for that is unreachable.

as a solution you may do something like this:

   
    switch notification.Platform {
		case PlatFormIos:
                        		if apnsClient == nil {
			apnsClient, err = apns.NewClient(
				ep,
				ConfGaurun.Ios.PemCertPath,
				ConfGaurun.Ios.PemKeyPath,
				time.Duration(ConfGaurun.Ios.Timeout)*time.Second,
			)
			if err != nil {
				msg := fmt.Sprintf("failed to connect to APNS: %s", err.Error())
				LogError.Error(msg)
				apnsClient = nil
				continue
			}
			apnsClient.TimeoutWaitError = time.Duration(ConfGaurun.Ios.TimeoutError) * time.Millisecond
		}

		if ConfGaurun.Ios.KeepAliveMax > 0 && loop > ConfGaurun.Ios.KeepAliveMax {
			apnsClient.Conn.Close()
			apnsClient.ConnTls.Close()
			apnsClient = nil
			loop = 0
			continue
		}
		loop++
			success = pushNotificationIos(notification, apnsClient)
			if !success {
				apnsClient = nil
			}
			retryMax = ConfGaurun.Ios.RetryMax


Instead of trying to connect in the beginning of the function.

**Comment by cubicdaiya** [comment]
@moadqassem Thank you for the suggestion. As you say there seems to be the point to be improved. I'll take it in the near future. Thank you again!

**Comment by moadqassem** [comment]
you are welcome, I already fix it my self locally and I would be glad to make a pull request for the enhancement if you are ok with it, if not its totally ok and thanks for the cool package anyway ;)

**Comment by cubicdaiya** [comment]
Patches welcome :)

**Comment by cubicdaiya** [comment]
fixed in https://github.com/mercari/gaurun/commit/6499a3a9b9c0ab793a3728092e577e7c468da6ed
