### ISSUE TITLE
Sometimes gaurun failed to send push notification in ios in spite of logging successed-push.

### ISSUE THREAD

**Issue by yss44** [mercari/gaurun#11]
Context:
* Using with docker.
* After running gaurun server for a while (4 days)
* In sending ios push notification

Gaurun logs successed-push, but device doesn't accept push notification. Then restart gaurun and resend the same message, gaurun also logs successed-push and device accept push notification immediately.

**Comment by cubicdaiya** [comment]
Would you please provide the `gaurun.toml` and request-json-body for reproducing?

**Comment by cubicdaiya** [comment]
Hi @yss44 ,

Is your `gaurun.toml` this?

https://github.com/yss44/docker-gaurun/blob/master/gaurun.toml

If so, assigning `ios.retry_max` to non-zero is recommended because `gaurun` always keeps TCP connection to APNs and APNs closes connection forcibly after a period of time. When connection is closed forcibly, `gaurun` will re-try to push if `retry_max` is non-zero.

**Comment by yss44** [comment]
Year! Thanks for your advice! I'll tri it !

**Comment by yss44** [comment]
I tryed to push with none-zero `ios.retry_max`, but the same behavior reproduced.

My `gaurun.toml` is below. 

```:toml
[core]
port = "1056"
workers = 2
queues = 8192
notification_max = 100

[api]
push_uri = "/push"
stat_go_uri = "/stat/go"
stat_app_uri = "/stat/app"
config_app_uri = "/config/app"

[android]
apikey = "APIKEY"
enabled = true
timeout = 5 # sec
retry_max = 1

[ios]
enabled = true
pem_cert_path = "cert.pem"
pem_key_path = "key.pem"
sandbox = false
timeout = 0 # sec
keepalive_max = 0
retry_max = 1
timeout_error = 500 # msec

[log]
access_log = "stdout"
error_log = "stderr"
level = "error"
```

And my request is this.

```
curl  -H 'Content-Type: application/json' -XPOST $(boot2docker ip):1056/push -d '{"notifications": [{"platform":1,"message":"test","token":["IOS_PUSH_TOKEN"],"sound":"default","expiry":3600,"extend":[{"key":"id","val":"1"}]}]}' 
```

**Comment by yss44** [comment]
And using docker container almost same container of [quai.io/yss44/docker-gaurun](https://quay.io/yss44/docker-gaurun).
(Unfortunately, the same container that reproduce behavior is private.)

**Comment by cubicdaiya** [comment]
@yss44 Thanks for the report. I'll investigate in the near feature.

**Comment by cubicdaiya** [comment]
@yss44 Hi, sorry for delay. I fixed this problem with the new paramter(`ios.keepalive_idle_timeout`). Please try `v0.4.0`.

**Comment by yss44** [comment]
Thank you for your Improvement! I'll try it soon!
