### ISSUE TITLE
Obtaining error feedback relating to invalid tokens

### ISSUE THREAD

**Issue by pennersr** [mercari/gaurun#115]
In order to be fully production ready, we would need to purge our database from invalid/expired tokens. Shouldn't there be an endpoint that can be queried to obtain error feedback relating to the push notifications that were processed?

**Update:** FWIW, to tackle this I rolled my own over at https://gitlab.com/pennersr/shove

**Comment by cubicdaiya** [comment]
Gaurun can output error log when push failures. User can use this log to purge invalid/expired tokens.
