### ISSUE TITLE
apns-push-type to the request header from ios13 to APNs.

### ISSUE THREAD

**Issue by junpayment** [mercari/gaurun#120]
It seems to be mandatory to pass `apns-push-type` to the request header from ios13 to APNs.
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns

How can I solve this with gaurun?

Thanks for the great product!

**Comment by cubicdaiya** [comment]
This PR looks to be necessary.

https://github.com/RobotsAndPencils/buford/pull/96

**Comment by junpayment** [comment]
RobotsAndPencils/buford#96 hasn't been merged yet, so I didn't check it, but I made a commit for PR for mercari/gaurun
https://github.com/nohana/gaurun/commit/ac8a831a39595d0a1b19f5e6552045f6eb357329

**Comment by catatsuy** [comment]
@junpayment We released https://github.com/mercari/gaurun/releases/tag/v0.11.1. Thank you for reporting.
