### ISSUE TITLE
Pass port number as exec argument

### ISSUE THREAD

**Issue by gamella** [mercari/gaurun#14]
Currently, port is controlled by setting file:

```
[core]
port = "4600"
workers = 8
queues = 8192
notification_max = 100
```

In our environment, gaurun is running on docker container. In our docker env, all port used by program is controlled and maitained by upper net container(ref.: http://blog-jp.alpaca.ai/entry/2015/10/28/095009).

To prevent the conflict of port, we would like to specify port number by Environment Variable(this is controlled in net container) like that:

`gauran -p %GAURUN_PORT -c setting.toml`

**Comment by cubicdaiya** [comment]
@gamella Why don't you use the [network port mapping](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/)?

**Comment by gamella** [comment]
Yes, port mapping is one solution. However, we use `-net=host` mode mainly, because we use some tricks to change the network configuration dynamically, and `-net=host` is good solution to change the network configuration dynamically.

**Comment by gamella** [comment]
Or we can re-generate toml file dynamically. This is alternative solution.

**Comment by cubicdaiya** [comment]
I see. As I'll consider whether introducing the option `-p`, take the approarch below for now. Or patches welcome.

> Or we can re-generate toml file dynamically. This is an alternative solution.

**Comment by cubicdaiya** [comment]
@gamella Added the option `-p` in #16. Thank you for the suggestion.

**Comment by gamella** [comment]
@cubicdaiya Thanks for quick support!
