### ISSUE TITLE
Support for new HTTP/2 Provider API for APNS

### ISSUE THREAD

**Issue by kuma-san** [mercari/gaurun#17]
Apple announced a new provider API for APNs based on HTTP/2 at WWDC 2015. 
Does gaurun have any plan to support this new Provider API in future? 

Thanks,

**Comment by cubicdaiya** [comment]
we have the plan to support this in the feature. But, not yet.

**Comment by nathany** [comment]
Take a look at Buford. It's a library for Apple's HTTP/2 Notification API. It shouldn't  be too difficult to substitute it for the apns library you are currently using.

https://github.com/RobotsAndPencils/buford

**Comment by cubicdaiya** [comment]
@nathany Thank you for the advice. I'll investigate in the near future.

**Comment by cubicdaiya** [comment]
@kuma-san We are working on the experimental branch (#18).

**Comment by cubicdaiya** [comment]
@kuma-san We merged #19 into the master branch. The next version would be release in the near future.

@nathany Thank you for the great work. buford is nice.

**Comment by nathany** [comment]
You're welcome. :-)

**Comment by kuma-san** [comment]
I was testing the experimental branch yesterday.
AWSOME!! Great work!
