### ISSUE TITLE
apns: Does not support 'content-available'?

### ISSUE THREAD

**Issue by tanatana** [mercari/gaurun#28]
It seems that gaurun dose not support 'content-available' property on apns. Is there any reasons to do so? (or I misundestanding?)

I wrote a small patch to use 'content-available' on gaurun and I would like to send a PR.

**Comment by cubicdaiya** [comment]
> It seems that gaurun dose not support 'content-available' property on apns. Is there any reasons to do so? (or I misundestanding?)

There is not any reasons in particular.

> I wrote a small patch to use 'content-available' on gaurun and I would like to send a PR.

Nice work. Patches welcome.

**Comment by tanatana** [comment]
Thanks for your reponse. I'm going to create a PR!
