### ISSUE TITLE
Send silent push notification with user-defined payload

### ISSUE THREAD

**Issue by kuma-san** [mercari/gaurun#33]
Is it possible to send silent push notification with user-defined payload such as:

```
{ 
  aps: {
          content-available: 1,
       },
   key: "value"
}
```

or

```
{ 
  aps: {
          alert: "",
          content-available: 1,
       }
   key: "value"
}
```

Thanks,

**Comment by cubicdaiya** [comment]
> Is it possible to send silent push notification with user-defined payload such as:

Now Gaurun does not accept the empty alert-body. But patches welcome.

On the other hand, it is possible to include user-defined payload with the parameter such as`extend`. For example,

```json
{
    "notifications" : [
        {
            ...
            "extend" : [
                { "key": "url", "val": "example.com" }, 
                { "key": "intent", "val": "SomeIntent" }
            ]
            ...
        }
    ]
}
```

The payload like above is converted like below.

```json
{
    "aps": {
        ...
    }
    "url": "example.com",
    "intent": "SomeIntent"
}
```

See [gaurun/SPEC.md#post-push](https://github.com/mercari/gaurun/blob/master/SPEC.md#post-push) for the detail.

**Comment by kuma-san** [comment]
Thanks for the reply @cubicdaiya !
I knew that I can include user-defined payload with extend, but in order to send silent push notification, I need to omit `alart` body.

**Comment by tugusuke** [comment]
@kuma-san 
Are you already working on this issue?

**Comment by kuma-san** [comment]
@tugusuke 
Not yet.
