### ISSUE TITLE
FCM(Firebase Cloud Messaging) support?

### ISSUE THREAD

**Issue by yoshiso** [mercari/gaurun#49]
Currently, FCM(Firebase Cloud Messaging) is strongly recommended by google . Is there any milestone to support for FCM?
https://developers.google.com/cloud-messaging/android/android-migrate-fcm

**Comment by cubicdaiya** [comment]
Yes. We have the plan for supporting FCM in the future. But the time is not still specific.

**Comment by yoshiso** [comment]
Thanks for your information!
FYI, we confirmed current gaurun works fine with FCM, with no additional changes.

**Comment by cubicdaiya** [comment]
FMC switching is [here](https://github.com/mercari/gaurun/pull/55). Now working in progress.

**Comment by cubicdaiya** [comment]
FCM is available in master now. refs: https://github.com/mercari/gaurun/pull/65
