### ISSUE TITLE
Service extensions support in iOS 10

### ISSUE THREAD

**Issue by yagitatsu** [mercari/gaurun#53]
I want to send rich media in push notification, but service extensions don't seem to be supported on gaurun.
Is there a milestone to support it ?
If the answer is no, I will try it.

see also:
- http://devstreaming.apple.com/videos/wwdc/2016/708tbh8wnspsg01hxwx/708/708_advanced_notifications.pdf
- https://developer.apple.com/reference/usernotifications/unnotificationserviceextension

**Comment by cubicdaiya** [comment]
> Is there a milestone to support it ?
> If the answer is no, I will try it.

Now we don't have the milestone to support it. But patches welcome.
